// // // File generated by FlutterFire CLI.
// // // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// // import 'package:flutter/foundation.dart'
// //     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// // /// Default [FirebaseOptions] for use with your Firebase apps.
// // ///
// // /// Example:
// // /// ```dart
// // /// import 'firebase_options.dart';
// // /// // ...
// // /// await Firebase.initializeApp(
// // ///   options: DefaultFirebaseOptions.currentPlatform,
// // /// );
// // /// ```
// // class DefaultFirebaseOptions {
// //   static FirebaseOptions get currentPlatform {
// //     if (kIsWeb) {
// //       throw UnsupportedError(
// //         'DefaultFirebaseOptions have not been configured for web - '
// //         'you can reconfigure this by running the FlutterFire CLI again.',
// //       );
// //     }
// //     switch (defaultTargetPlatform) {
// //       case TargetPlatform.android:
// //         return android;
// //       case TargetPlatform.macOS:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions have not been configured for macos - '
// //           'you can reconfigure this by running the FlutterFire CLI again.',
// //         );
// //       case TargetPlatform.windows:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions have not been configured for windows - '
// //           'you can reconfigure this by running the FlutterFire CLI again.',
// //         );
// //       case TargetPlatform.iOS:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions have not been configured for linux - '
// //           'you can reconfigure this by running the FlutterFire CLI again.',
// //         );
// //       default:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions are not supported for this platform.',
// //         );
// //     }
// //   }

// //   static const FirebaseOptions android = FirebaseOptions(
// // apiKey: 'AIzaSyAdmxLITglY4qAB051OCnOO0TRQ8gMVPtc',
// // appId: '1:84139905796:web:385993cbe0608ad7f7f651',
// // messagingSenderId: '84139905796',
// // projectId: 'godiets',
// // storageBucket: 'godiets.appspot.com',
// //   );
// // }
// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;

//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAdmxLITglY4qAB051OCnOO0TRQ8gMVPtc',
//     appId: '1:84139905796:web:385993cbe0608ad7f7f651',
//     messagingSenderId: '84139905796',
//     projectId: 'godiets',
//     storageBucket: 'godiets.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(

//   );
// }
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdmxLITglY4qAB051OCnOO0TRQ8gMVPtc',
    appId: '1:84139905796:web:385993cbe0608ad7f7f651',
    messagingSenderId: '84139905796',
    projectId: 'godiets',
    storageBucket: 'godiets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmxLITglY4qAB051OCnOO0TRQ8gMVPtc',
    appId: '1:84139905796:web:385993cbe0608ad7f7f651',
    messagingSenderId: '84139905796',
    projectId: 'godiets',
    storageBucket: 'godiets.appspot.com',
  );
}
